[package]
name = "inbuxa-migrate"
description = "Account migration and backup for inbuxa"
version = "2026.9.30"
authors = ["Coffey Labs LLC <legal@coffeylabs.org>"]
license = "Apache-2.0 OR MIT"
repository = "https://git.coffeylabs.org/inbuxa/inbuxa-migrate"
homepage = "https://git.coffeylabs.org/inbuxa/inbuxa-migrate"
edition = "2024"
readme = "README.md"

[[bin]]
name = "inbuxa-migrate"
path = "src/main.rs"

[features]
default = ["bundled-sqlite"]
bundled-sqlite = ["rusqlite/bundled"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "2.14", features = ["serde"] }
rusqlite = { version = "0.40", features = ["blob"] }
blake3 = "1.8.5"
time = { version = "0.3.47", features = ["serde-well-known", "macros"] }
url= "2.5.8"
thiserror  = "2.0.18"
ureq = { version = "3.3.0", default-features = false, features = ["json", "gzip", "rustls-no-provider", "platform-verifier"] }
clap = { version = "4.6.1", features = ["derive"] }
crossbeam-channel = "0.5.15"
num_cpus = "1.17.0"
encodify = "1.0"
mail-parser = "0.11.3"
calcard = "0.3"
rustls = { version = "0.23.40", default-features = false, features = ["aws-lc-rs", "std", "tls12", "logging"] }
rustls-platform-verifier = "0.7"
regex  = "1.13"
flate2 = "1.1.9"
quick-xml = "0.42"
chrono = { version = "0.4", default-features = false, features = ["std"] }
chrono-tz = { version = "0.10", default-features = false }
psl = "2.1.226"

[dev-dependencies]
mockito = "1.7.2"
tempfile = "3.13"
testcontainers = { version = "0.28", features = ["blocking"] }
